//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4016
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStoryProjectEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneStoryProjectEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BuilderDialog_movedown1 {
            get {
                object obj = ResourceManager.GetObject("BuilderDialog_movedown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BuilderDialog_moveup1 {
            get {
                object obj = ResourceManager.GetObject("BuilderDialog_moveup1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap DragDropHandle {
            get {
                object obj = ResourceManager.GetObject("DragDropHandle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoLtrHS {
            get {
                object obj = ResourceManager.GetObject("GoLtrHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GoRtlHS {
            get {
                object obj = ResourceManager.GetObject("GoRtlHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Hyperlink {
            get {
                object obj = ResourceManager.GetObject("Hyperlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{1}&apos; नाम का एक प्रजैक्ट दूसरे फ़ोल्‍डर में हो चुका है। अगर यह नया प्रोजैक्ट इसी नाम के साथ बनता है, तब दूसरा प्रोजैक्‍ट नहीं खोल पाएगा, जो &apos;{2}&apos; फ़ोल्‍डर में है।{0}{0}क्‍या आप नया प्रोजैक्ट फिर भी बनाना चाहते हैं?.
        /// </summary>
        internal static string IDS_AboutToStrandProject {
            get {
                return ResourceManager.GetString("IDS_AboutToStrandProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow these steps to use the Adapt It program to translate the story into English:{0}{0}1) Switch to the Adapt It program using Alt+Tab keys{0}2) Select the &apos;{1}&apos; project and click the &apos;Next&apos; button (if a file is already open in Adapt It, then choose the &apos;File&apos; menu, &apos;Close Project&apos; command and then the &apos;File&apos; menu, &apos;Start Working&apos; command first).{0}3) Select the &apos;{2}.xls&apos; document to open and press the &apos;Finished&apos; button.{0}4) When you see this story in the adaptation window, then translate it into English [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_AdaptationInstructions {
            get {
                return ResourceManager.GetString("IDS_AdaptationInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}5) When you&apos;re finished, return to this window and click the &apos;Yes&apos; button to re-import the translated English text back into the English fields.{0}{0}Have you finished translating the story to English and are ready to import it into the English fields?.
        /// </summary>
        internal static string IDS_AdaptationInstructionsContinue {
            get {
                return ResourceManager.GetString("IDS_AdaptationInstructionsContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Adapt It file for the project &apos;{0}&apos;, story &apos;{1}&apos; already exists. If you want to delete that file and do the English translation of the story all over again, then click &apos;Yes&apos;. If you just want to try to import the existing file again, choose &apos;No&apos;. Otherwise, click &apos;Cancel&apos; to stop this command..
        /// </summary>
        internal static string IDS_AdaptItFileAlreadyExists {
            get {
                return ResourceManager.GetString("IDS_AdaptItFileAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;एक-कहानी&quot; प्रोजैक्‍ट ऐडिटर.
        /// </summary>
        internal static string IDS_Caption {
            get {
                return ResourceManager.GetString("IDS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the Story Crafter.
        /// </summary>
        internal static string IDS_ChooseTheStoryCrafter {
            get {
                return ResourceManager.GetString("IDS_ChooseTheStoryCrafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name you want to give this project (e.g. the language name)..
        /// </summary>
        internal static string IDS_EnterProjectName {
            get {
                return ResourceManager.GetString("IDS_EnterProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;नई कहानी का नाम यहीं टाइप करके &apos;ऐटर&apos; बटन दबाओ&gt;.
        /// </summary>
        internal static string IDS_EnterStoryName {
            get {
                return ResourceManager.GetString("IDS_EnterStoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to नई कहानी का नाम यहीं टाइप करके &apos;ऐटर&apos; बटन दबाओ.
        /// </summary>
        internal static string IDS_EnterStoryToAdd {
            get {
                return ResourceManager.GetString("IDS_EnterStoryToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;The data from Adapt It doesn&apos;t appear to match what&apos;s in the story.{0}In verse number {2}, I was expecting \&quot;{3}\&quot;, but got \&quot;{4}\&quot; instead.{0}If you&apos;ve made changes in the story or the {1} back-translation, then you need to re-export the story or {1} back-translation to Adapt It,{0}re-process the file there, and then try to import again.&quot;.
        /// </summary>
        internal static string IDS_ErrorInAdaptation {
            get {
                return ResourceManager.GetString("IDS_ErrorInAdaptation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file &apos;{0}&apos; is locked. Is it read-only? Or opened in some other program? Unlock it and try again. Or try to save it as a different name..
        /// </summary>
        internal static string IDS_FileLockedMessage {
            get {
                return ResourceManager.GetString("IDS_FileLockedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;From {0}.
        /// </summary>
        internal static string IDS_FromNatlLanguage {
            get {
                return ResourceManager.GetString("IDS_FromNatlLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;From {0} (for Discourse Charting).
        /// </summary>
        internal static string IDS_FromStoryForDiscourseCharting {
            get {
                return ResourceManager.GetString("IDS_FromStoryForDiscourseCharting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to काम करने के लिए आपको लॉग-इन करना है। &apos;Project&apos; मेनू, &apos;Settings&apos; पर क्‍लिक करो और अपना नाम चुनकर &apos;लॉग-इन&apos; बटन दबाओ।.
        /// </summary>
        internal static string IDS_HaveToLogInToContinue {
            get {
                return ResourceManager.GetString("IDS_HaveToLogInToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्‍या यह कहानी बाइबल से है?.
        /// </summary>
        internal static string IDS_IsThisStoryFromTheBible {
            get {
                return ResourceManager.GetString("IDS_IsThisStoryFromTheBible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} &amp;language fields.
        /// </summary>
        internal static string IDS_LanguageFields {
            get {
                return ResourceManager.GetString("IDS_LanguageFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to जो &apos;{0}&apos; फ़ोलडर में है.
        /// </summary>
        internal static string IDS_LocatedInFolder {
            get {
                return ResourceManager.GetString("IDS_LocatedInFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to be logged in as a &apos;Crafter&apos; to add stories. To login, click &apos;Project&apos;, &apos;Settings&apos;.
        /// </summary>
        internal static string IDS_LogInAsCrafter {
            get {
                return ResourceManager.GetString("IDS_LogInAsCrafter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneStory Editor -- {0} Story Project.
        /// </summary>
        internal static string IDS_MainFrameTitle {
            get {
                return ResourceManager.GetString("IDS_MainFrameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} back-translation of the story.
        /// </summary>
        internal static string IDS_NationalBtOfStory {
            get {
                return ResourceManager.GetString("IDS_NationalBtOfStory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem initializing Sword (the Net Bible viewer):{0}{0}{1}.
        /// </summary>
        internal static string IDS_NeedToReboot {
            get {
                return ResourceManager.GetString("IDS_NeedToReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already have a project with the name, &apos;{0}&apos;. Do you want to delete the existing one?.
        /// </summary>
        internal static string IDS_OverwriteProject {
            get {
                return ResourceManager.GetString("IDS_OverwriteProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}  निर्देश मिलने के लिए &apos;F1&apos; बटन दबाओ.
        /// </summary>
        internal static string IDS_PressF1ForInstructions {
            get {
                return ResourceManager.GetString("IDS_PressF1ForInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is corrupted. No &apos;StoryCrafterMemberID&apos; record found. Send to bob_eaton@sall.com for help..
        /// </summary>
        internal static string IDS_ProjectFileCorrupted {
            get {
                return ResourceManager.GetString("IDS_ProjectFileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is corrupted. No &apos;CraftingInfo&apos; record found. Send to bob_eaton@sall.com for help..
        /// </summary>
        internal static string IDS_ProjectFileCorruptedNoCraftingInfo {
            get {
                return ResourceManager.GetString("IDS_ProjectFileCorruptedNoCraftingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to क्‍या बंद करने से पहले सेव किया जाए?.
        /// </summary>
        internal static string IDS_SaveChanges {
            get {
                return ResourceManager.GetString("IDS_SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कहानी.
        /// </summary>
        internal static string IDS_Story {
            get {
                return ResourceManager.GetString("IDS_Story", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to कहानी:.
        /// </summary>
        internal static string IDS_StoryColon {
            get {
                return ResourceManager.GetString("IDS_StoryColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;{0} back-translation field.
        /// </summary>
        internal static string IDS_StoryLanguageField {
            get {
                return ResourceManager.GetString("IDS_StoryLanguageField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} story text.
        /// </summary>
        internal static string IDS_StoryText {
            get {
                return ResourceManager.GetString("IDS_StoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to अगर अगले स्‍टेट में जाएं, तो इसके बाद आप इस कहानी को तब तक नहीं बदल सकते हैं, जब तक {0} अपने काम इस पर पूरा नहीं किया। क्‍या आप पक्‍का हैं कि अगले स्‍टेट (अनिकि &apos;{1}&apos; स्‍टेट) में जाएँ?.
        /// </summary>
        internal static string IDS_TerminalTransitionMessage {
            get {
                return ResourceManager.GetString("IDS_TerminalTransitionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue! Cause: {0}.
        /// </summary>
        internal static string IDS_UnableToContinue {
            get {
                return ResourceManager.GetString("IDS_UnableToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy text to the clipboard!{0}{0}{1}{0}{0}{2}.
        /// </summary>
        internal static string IDS_UnableToCopyText {
            get {
                return ResourceManager.GetString("IDS_UnableToCopyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to प्रोजैक्ट नाम के बिना नया प्रोजैक्ट नहीं बन सकता है!.
        /// </summary>
        internal static string IDS_UnableToCreateProjectWithoutName {
            get {
                return ResourceManager.GetString("IDS_UnableToCreateProjectWithoutName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; नामक कहानी नहीं है। क्‍या उस नाम की नई कहानी जोड़ दिया जाए?.
        /// </summary>
        internal static string IDS_UnableToFindStoryAdd {
            get {
                return ResourceManager.GetString("IDS_UnableToFindStoryAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to import the project &apos;{1}&apos;{0}{0}{2}{0}{0}Contact bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_UnableToImportProject {
            get {
                return ResourceManager.GetString("IDS_UnableToImportProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the member list{0}{0}{1}{0}{0}Contact bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_UnableToOpenMemberList {
            get {
                return ResourceManager.GetString("IDS_UnableToOpenMemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open project &apos;{1}&apos;{0}{0}{2}{0}{0}{3}{0}{0}Send the project file along with the error message to bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_UnableToOpenProjectFile {
            get {
                return ResourceManager.GetString("IDS_UnableToOpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the project file &apos;{1}&apos;{0}{0}{2}.
        /// </summary>
        internal static string IDS_UnableToSave {
            get {
                return ResourceManager.GetString("IDS_UnableToSave", resourceCulture);
            }
        }
    }
}
