//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStoryProjectEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OneStoryProjectEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!--StoryProject@version changed from 1.4 to 1.5--&gt;
        ///  &lt;xsl:template match=&quot;StoryProject/@version&quot;&gt;
        ///    &lt;xsl:attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1_4_to_1_5 {
            get {
                return ResourceManager.GetString("_1_4_to_1_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aikb-{0}-{1}.
        /// </summary>
        internal static string AdaptItProjectRepositoryFormat {
            get {
                return ResourceManager.GetString("AdaptItProjectRepositoryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddTableHS {
            get {
                object obj = ResourceManager.GetObject("AddTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AddToFavoritesHS {
            get {
                object obj = ResourceManager.GetObject("AddToFavoritesHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Arrow {
            get {
                object obj = ResourceManager.GetObject("Arrow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio files|*.mp3;*.wav;*.wma|All files|*.*.
        /// </summary>
        internal static string AudioFileSearchFilter {
            get {
                return ResourceManager.GetString("AudioFileSearchFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BuilderDialog_movedown1 {
            get {
                object obj = ResourceManager.GetObject("BuilderDialog_movedown1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BuilderDialog_moveup1 {
            get {
                object obj = ResourceManager.GetObject("BuilderDialog_moveup1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap CopyHS {
            get {
                object obj = ResourceManager.GetObject("CopyHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveFirstHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveFirstHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveLastHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveLastHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MoveNextHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MoveNextHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DataContainer_MovePreviousHS {
            get {
                object obj = ResourceManager.GetObject("DataContainer_MovePreviousHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OneStory Editor Projects.
        /// </summary>
        internal static string DefMyDocsSubfolder {
            get {
                return ResourceManager.GetString("DefMyDocsSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DeleteHS {
            get {
                object obj = ResourceManager.GetObject("DeleteHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap DragDropHandle {
            get {
                object obj = ResourceManager.GetObject("DragDropHandle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Edit_Undo {
            get {
                object obj = ResourceManager.GetObject("Edit_Undo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditInformationHS {
            get {
                object obj = ResourceManager.GetObject("EditInformationHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap EditTableHS {
            get {
                object obj = ResourceManager.GetObject("EditTableHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillDownHS {
            get {
                object obj = ResourceManager.GetObject("FillDownHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FillUpHS {
            get {
                object obj = ResourceManager.GetObject("FillUpHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gradient {
            get {
                object obj = ResourceManager.GetObject("gradient", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap graphhs {
            get {
                object obj = ResourceManager.GetObject("graphhs", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button id=&quot;{0}&quot; onClick=&quot;{1}&quot;&gt;{2}&lt;/button&gt;.
        /// </summary>
        internal static string HTML_Button {
            get {
                return ResourceManager.GetString("HTML_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button id=&quot;{0}&quot; class=&quot;{1}&quot; onClick=&quot;{2}&quot;&gt;{3}&lt;/button&gt;.
        /// </summary>
        internal static string HTML_ButtonClass {
            get {
                return ResourceManager.GetString("HTML_ButtonClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button id=&quot;{0}&quot; onmouseup=&quot;{1}&quot; style=&quot;height:20px; width:20px;&quot;&gt;{2}&lt;/button&gt;.
        /// </summary>
        internal static string HTML_ButtonLineOptions {
            get {
                return ResourceManager.GetString("HTML_ButtonLineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;button id=&quot;{0}&quot; name=&quot;{1}&quot; onMouseUp=&quot;{2}&quot; title=&quot;{3}&quot;&gt;{4}&lt;/button&gt;.
        /// </summary>
        internal static string HTML_ButtonToolTip {
            get {
                return ResourceManager.GetString("HTML_ButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script&gt;
        ///    function OnBibRefJump(link) {
        ///        window.external.OnBibRefJump(link.name);
        ///        return false; // cause the href navigation to not happen
        ///    }
        ///    function OnVerseLineJump(link) {
        ///        window.external.OnVerseLineJump(link.name);
        ///        return false; // cause the href navigation to not happen
        ///    }
        ///	
        ///    var s_key = 83;
        ///    var f5_key = 116;
        ///    function OnKeyDown() {
        ///        if (window.event.keyCode == f5_key) {
        ///            // let the form handle it
        ///            window. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_DOM_Prefix {
            get {
                return ResourceManager.GetString("HTML_DOM_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///function OnBibRefJump(btn)
        ///{
        ///  window.external.OnBibRefJump(btn.id);
        ///  return false; // cause the href navigation to not happen
        ///}
        ///function OnLineOptionsButton(btn)
        ///{
        ///  window.external.OnLineOptionsButton(btn.id);
        ///  return false;
        ///}
        ///function OnVerseLineJump(link)
        ///{
        ///  window.external.OnVerseLineJump(link.name);
        ///  return false; // cause the href navigation to not happen
        ///}
        ///function OnKeyDown(textarea)
        ///{
        ///  if (window.event.keyCode == 116)
        ///  {
        ///    // let the form [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_DOM_PrefixPresentation {
            get {
                return ResourceManager.GetString("HTML_DOM_PrefixPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;em&gt;{0}&lt;/em&gt;.
        /// </summary>
        internal static string HTML_EmphasizedText {
            get {
                return ResourceManager.GetString("HTML_EmphasizedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///{0}
        ///&lt;head&gt;
        ///{1}
        ///&lt;/head&gt;
        ///&lt;body onKeyDown=&quot;return OnKeyDown();&quot; onscroll=&quot;window.external.OnScroll()&quot;&gt;
        ///{2}
        ///&lt;/body&gt;
        ///{3}
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HTML_Header {
            get {
                return ResourceManager.GetString("HTML_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;
        ///{0}
        ///&lt;head&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///{1}
        ///&lt;/script&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///{2}
        ///&lt;/body&gt;
        ///&lt;script&gt;
        ///{3}
        ///&lt;/script&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string HTML_HeaderPresentation {
            get {
                return ResourceManager.GetString("HTML_HeaderPresentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot; target=&quot;_blank&quot;&gt;here&lt;/a&gt; .
        /// </summary>
        internal static string HTML_HttpLink {
            get {
                return ResourceManager.GetString("HTML_HttpLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .{0} {{
        ///      font-family: &quot;{1}&quot;;
        ///      font-size: {2} pt;
        ///      color: {3};
        ///      direction: {4};
        ///      text-align: {5};
        ///  }}.
        /// </summary>
        internal static string HTML_LangStyle {
            get {
                return ResourceManager.GetString("HTML_LangStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .{0} {{
        ///      font-family: &quot;{1}&quot;;
        ///      font-size: {2} pt;
        ///  }}.
        /// </summary>
        internal static string HTML_LangStyleCenter {
            get {
                return ResourceManager.GetString("HTML_LangStyleCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;conNote.jumpToLine&quot; name=&quot;{0}&quot; class=&quot;{1}&quot; onClick=&quot;return OnVerseLineJump(this);&quot;&gt;{2}&lt;/a&gt;.
        /// </summary>
        internal static string HTML_LinkJumpLine {
            get {
                return ResourceManager.GetString("HTML_LinkJumpLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;bibleViewer.setReference&quot; name=&quot;{0}&quot; onClick=&quot;return OnBibRefJump(this);&quot;&gt;{0}&lt;/a&gt;.
        /// </summary>
        internal static string HTML_LinkJumpTargetBibleReference {
            get {
                return ResourceManager.GetString("HTML_LinkJumpTargetBibleReference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p class=&quot;{0}&quot;&gt;{1}&lt;/p&gt;.
        /// </summary>
        internal static string HTML_ParagraphText {
            get {
                return ResourceManager.GetString("HTML_ParagraphText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p id=&quot;{0}&quot; class=&quot;{1}&quot;&gt;{2}&lt;/p&gt;.
        /// </summary>
        internal static string HTML_ParagraphTextId {
            get {
                return ResourceManager.GetString("HTML_ParagraphTextId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;script type=&quot;text/javascript&quot;&gt;
        ///  var textareas = document.getElementsByTagName(&quot;textarea&quot;);
        ///  for (var i=0; i &lt; textareas.length; i++) {
        ///    textareas[i].onmousedown = function() { return window.external.OnTextareaMouseDown(this.id, this.value); };
        ///	textareas[i].onkeyup = function() { return window.external.TextareaOnKeyUp(this.id, this.value); };
        ///	textareas[i].ondragover = function() { window.event.returnValue=false; };
        ///	textareas[i].ondrop = function () { window.external.CopyScriptureReference(this [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_Script_AddTextareaMouseDown {
            get {
                return ResourceManager.GetString("HTML_Script_AddTextareaMouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;SPAN class=&quot;{0} {1}&quot;&gt;{2}&lt;/SPAN&gt;.
        /// </summary>
        internal static string HTML_SpanLangQuote {
            get {
                return ResourceManager.GetString("HTML_SpanLangQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;style type=&quot;text/css&quot;&gt;
        ///  body    {{ margin:0 }}
        ///  textarea {{ 
        ///      width:100%; 
        ///      overflow:visible;
        ///      resize:none;
        ///  }}
        ///  table {{
        ///   font-size: {0};
        ///  }}
        ///  button 
        ///  {{
        ///    font-size: {1};
        ///    padding: 0 2px;
        ///    overflow: visible;
        ///  }}  
        ///  p 
        ///  {{
        ///    margin-top: 0em; 
        ///    margin-bottom: 0em;
        ///  }} 
        ///  {2}
        ///  .hasPlaceholder {{
        ///     color: #777;
        ///  }}
        ///  .Retelling {{
        ///	color: {3}
        ///  }}
        ///  .TestQuestion {{
        ///	color: {4}
        ///  }}
        ///  .TestQuestionAnswer {{
        ///	color: {5}
        ///  }}
        ///  .r [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HTML_StyleDefinition {
            get {
                return ResourceManager.GetString("HTML_StyleDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;table style=&quot;width:100%;&quot; border=&quot;1&quot; cellspacing=&quot;0&quot; cellpadding=&quot;0&quot;&gt;
        ///  {0}
        ///  &lt;/table&gt;.
        /// </summary>
        internal static string HTML_Table {
            get {
                return ResourceManager.GetString("HTML_Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;table style=&quot;width:100%;&quot; border=&quot;1&quot;&gt;
        ///  {0}
        ///  &lt;/table&gt;.
        /// </summary>
        internal static string HTML_TableBorder {
            get {
                return ResourceManager.GetString("HTML_TableBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td&gt;{0}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCell {
            get {
                return ResourceManager.GetString("HTML_TableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td class=&quot;{0}&quot;&gt;&lt;font color=&quot;{1}&quot;&gt;{2}&lt;/font&gt;&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellClass {
            get {
                return ResourceManager.GetString("HTML_TableCellClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;100%&quot;&gt;{0}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellForTextArea {
            get {
                return ResourceManager.GetString("HTML_TableCellForTextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellId {
            get {
                return ResourceManager.GetString("HTML_TableCellId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td NOWRAP&gt;{0}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellNoWrap {
            get {
                return ResourceManager.GetString("HTML_TableCellNoWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td align=&quot;right&quot;&gt;{0}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellRightAlign {
            get {
                return ResourceManager.GetString("HTML_TableCellRightAlign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;{0}%&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidth {
            get {
                return ResourceManager.GetString("HTML_TableCellWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;{0}%&quot; valign=&quot;top&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidthAlignTop {
            get {
                return ResourceManager.GetString("HTML_TableCellWidthAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{0}&quot; width=&quot;{1}%&quot; ondragover=&quot;window.event.returnValue=false&quot; ondrop=&quot;window.external.AddScriptureReference(this.id)&quot; onmouseup=&quot;OnEmptyAnchorClick(this.id);&quot;&gt;{2}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidthDropAnchor {
            get {
                return ResourceManager.GetString("HTML_TableCellWidthDropAnchor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td id=&quot;{0}&quot; width=&quot;{1}%&quot;&gt;{2}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidthId {
            get {
                return ResourceManager.GetString("HTML_TableCellWidthId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWidthPixels {
            get {
                return ResourceManager.GetString("HTML_TableCellWidthPixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td colspan=&quot;{0}&quot;&gt;{1}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWithSpan {
            get {
                return ResourceManager.GetString("HTML_TableCellWithSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;td width=&quot;{0}%&quot; colspan=&quot;{1}&quot;&gt;{2}&lt;/td&gt;.
        /// </summary>
        internal static string HTML_TableCellWithSpanAndWidth {
            get {
                return ResourceManager.GetString("HTML_TableCellWithSpanAndWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table id=&quot;{0}&quot; style=&quot;width:100%;&quot;&gt;
        ///{1}
        ///&lt;/table&gt;.
        /// </summary>
        internal static string HTML_TableForLine {
            get {
                return ResourceManager.GetString("HTML_TableForLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;table style=&quot;width:100%;&quot;&gt;
        ///{0}
        ///&lt;/table&gt;.
        /// </summary>
        internal static string HTML_TableNoBorder {
            get {
                return ResourceManager.GetString("HTML_TableNoBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   &lt;tr&gt;
        ///    {0}
        ///  &lt;/tr&gt;
        ///    .
        /// </summary>
        internal static string HTML_TableRow {
            get {
                return ResourceManager.GetString("HTML_TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr BGCOLOR=&quot;{0}&quot;&gt;{1}&lt;/tr&gt;.
        /// </summary>
        internal static string HTML_TableRowColor {
            get {
                return ResourceManager.GetString("HTML_TableRowColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;{0}&quot;&gt;{1}&lt;/tr&gt;    .
        /// </summary>
        internal static string HTML_TableRowId {
            get {
                return ResourceManager.GetString("HTML_TableRowId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;tr id=&quot;{0}&quot; BGCOLOR=&quot;{1}&quot;&gt;{2}&lt;/tr&gt;    .
        /// </summary>
        internal static string HTML_TableRowIdColor {
            get {
                return ResourceManager.GetString("HTML_TableRowIdColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea id=&quot;{0}&quot; class=&quot;{1}&quot;&gt;{2}&lt;/textarea&gt;.
        /// </summary>
        internal static string HTML_Textarea {
            get {
                return ResourceManager.GetString("HTML_Textarea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;textarea id=&quot;{0}&quot; class=&quot;{1}&quot;&gt;{2}&lt;/textarea&gt;.
        /// </summary>
        internal static string HTML_TextareaWithRefDrop {
            get {
                return ResourceManager.GetString("HTML_TextareaWithRefDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hyperlink {
            get {
                object obj = ResourceManager.GetObject("Hyperlink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Adapt It converter named &apos;{0}&apos; doesn&apos;t exist! You probably need to do &apos;Project&apos;, &apos;Settings&apos; and configure it on the &apos;Adapt It&apos; tab.
        /// </summary>
        internal static string IDS_AdaptItConverterDoesntExist {
            get {
                return ResourceManager.GetString("IDS_AdaptItConverterDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} to {1} adaptations.
        /// </summary>
        internal static string IDS_AdaptItProjectFolderFormat {
            get {
                return ResourceManager.GetString("IDS_AdaptItProjectFolderFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Yes&apos; if you want to enter the results for another UNS retelling test, or click &apos;No&apos; to send to the consultant for checking.
        /// </summary>
        internal static string IDS_AddAnotherTestQuery {
            get {
                return ResourceManager.GetString("IDS_AddAnotherTestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Yes&apos; to add boxes for answers to the testing questions? Or click &apos;No&apos; if you already have boxes (you might have them if you had earlier clicked &quot;Edit&quot;, &quot;Add story test results&quot;).
        /// </summary>
        internal static string IDS_AddInferenceTestQuery {
            get {
                return ResourceManager.GetString("IDS_AddInferenceTestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Yes&apos; to add boxes for the retelling lines? Or click &apos;No&apos; if you already have boxes (you might have them if you had earlier clicked &quot;Edit&quot;, &quot;Add retelling test results&quot;).
        /// </summary>
        internal static string IDS_AddRetellingTestQuery {
            get {
                return ResourceManager.GetString("IDS_AddRetellingTestQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only delete a key term from the editable key term (i.e. &quot;My Biblical Terms&quot;) list, which is not currently selected..
        /// </summary>
        internal static string IDS_CanDeleteOnlyFromMyBiblicalTerms {
            get {
                return ResourceManager.GetString("IDS_CanDeleteOnlyFromMyBiblicalTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program can&apos;t make this change right now. If this error continues, contact bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_CantEditPanoramaView {
            get {
                return ResourceManager.GetString("IDS_CantEditPanoramaView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Yes&apos; to enter UNS test results now or click &apos;No&apos; to send the story to the consultant first for checking..
        /// </summary>
        internal static string IDS_CheckForSkipToUnsCheck {
            get {
                return ResourceManager.GetString("IDS_CheckForSkipToUnsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are there any key terms in this story that you should check? To check key terms, right-click on an anchor button and choose the &apos;Edit Key Terms&apos; command. Click the &quot;Retry&quot; button to continue on to the next state. Click the &apos;Cancel&apos; button to stay in this state to look for key terms to check..
        /// </summary>
        internal static string IDS_CheckOnKeyTerms {
            get {
                return ResourceManager.GetString("IDS_CheckOnKeyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the key term:{0}{1}.
        /// </summary>
        internal static string IDS_ConfirmDeleteKeyTerm {
            get {
                return ResourceManager.GetString("IDS_ConfirmDeleteKeyTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file that stores the view settings must be deleted to upgrade to the new format (these customizations were done via &apos;Select State&apos;, &apos;Advanced&apos; button, and then right-click on a state button to check or uncheck view fields for a given state). Because of this, it means that you will need to redo the settings..
        /// </summary>
        internal static string IDS_ConfirmDeleteStateTransitions {
            get {
                return ResourceManager.GetString("IDS_ConfirmDeleteStateTransitions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;meta name=ProgId content=Word.Document&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 11&quot;&gt;
        ///&lt;meta name=Originator content=&quot;Microsoft Word 11&quot;&gt;
        ///&lt;link rel=File-List href=&quot;OneStory%20Editor%20is%20Copyright_files/filelist.xml&quot;&gt;
        ///&lt;title&gt;OneStory Editor is Copyright © 2009-2013 SIL International &lt;/title&gt;
        ///&lt;!--[if gte mso 9]&gt;&lt;xml&gt;
        /// &lt;o:DocumentProperties&gt;
        ///  &lt;o:Author&gt;Bob Eaton&lt;/o:Author&gt;
        ///  &lt;o:LastAuthor&gt;Bob Eaton&lt;/o:LastAuthor&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_CopyrightInfo {
            get {
                return ResourceManager.GetString("IDS_CopyrightInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In order to add or edit key terms, you have to begin using a local copy of one of the existing key
        ///terms list (i.e. a copy generated, for example, from the Paratext &quot;Major Key Terms&quot; or &quot;All Key 
        ///Terms&quot; lists or one customized by your entity). At this point, you may want to click &apos;Cancel&apos; 
        ///here and then click the &quot;Select Key Terms List&quot; button to select one of the other, existing key 
        ///terms lists to see if the term you want is present in one of them. If you don&apos;t find the term in 
        ///one of those lists an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_CreateMyBiblicalTermsQuery {
            get {
                return ResourceManager.GetString("IDS_CreateMyBiblicalTermsQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\adeflang1081\ansi\ansicpg1252\uc1\adeff0\deff0\stshfdbch0\stshfloch0\stshfhich0\stshfbi0\deflang1033\deflangfe1033{\fonttbl{\f0\froman\fcharset0\fprq2{\*\panose 02020603050405020304}Times New Roman;}{\f312\froman\fcharset238\fprq2 Times New Roman CE;}{\f313\froman\fcharset204\fprq2 Times New Roman Cyr;}
        ///{\f315\froman\fcharset161\fprq2 Times New Roman Greek;}{\f316\froman\fcharset162\fprq2 Times New Roman Tur;}{\f317\fbidi \froman\fcharset177\fprq2 Times New Roman (Hebrew);}{\f318\fbidi \froman\fchar [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_DefaultPanoramaFrontMatter {
            get {
                return ResourceManager.GetString("IDS_DefaultPanoramaFrontMatter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LanguageDepot.org [resumable sync].
        /// </summary>
        internal static string IDS_DefaultRepoServer {
            get {
                return ResourceManager.GetString("IDS_DefaultRepoServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an automated message from OSE v{0}:
        ///
        ///{1}.
        /// </summary>
        internal static string IDS_EmailMessageBody {
            get {
                return ResourceManager.GetString("IDS_EmailMessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [OSE says]: {0}.
        /// </summary>
        internal static string IDS_EmailSubjectLine {
            get {
                return ResourceManager.GetString("IDS_EmailSubjectLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;From {0} (for Discourse Charting).
        /// </summary>
        internal static string IDS_FromStoryForDiscourseCharting {
            get {
                return ResourceManager.GetString("IDS_FromStoryForDiscourseCharting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This story has already reached the final state. If you mean to go to some previous state, click the &apos;Select State&apos; menu at the top of the window and choose the previous state you want to go to..
        /// </summary>
        internal static string IDS_GoBackwardsYoungMan {
            get {
                return ResourceManager.GetString("IDS_GoBackwardsYoungMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file has an ill-formed Anchor! Wasn&apos;t expecting to see &apos;{0}&apos;. Contact bob_eaton@sall.com and mention which the project name..
        /// </summary>
        internal static string IDS_IllFormedJumpTarget {
            get {
                return ResourceManager.GetString("IDS_IllFormedJumpTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process Key Terms: cause: {0}{0}{1}.
        /// </summary>
        internal static string IDS_KeyTermsProblem {
            get {
                return ResourceManager.GetString("IDS_KeyTermsProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will need to log in as a coach to be able to respond to the CIT/LSR comments.
        /// </summary>
        internal static string IDS_LoginAsCoach {
            get {
                return ResourceManager.GetString("IDS_LoginAsCoach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stories.
        /// </summary>
        internal static string IDS_MainStoriesSet {
            get {
                return ResourceManager.GetString("IDS_MainStoriesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The network repository must be identical (a &quot;clone&quot;) of the repository in the local machine. Contact your workshop advisor..
        /// </summary>
        internal static string IDS_MustBeCloneRepo {
            get {
                return ResourceManager.GetString("IDS_MustBeCloneRepo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://db.tt/4VwBmut.
        /// </summary>
        internal static string IDS_MyDropboxReferalString {
            get {
                return ResourceManager.GetString("IDS_MyDropboxReferalString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problem initializing Sword (the Net Bible viewer):{0}{0}{1}.
        /// </summary>
        internal static string IDS_NeedToReboot {
            get {
                return ResourceManager.GetString("IDS_NeedToReboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html xmlns:v=&quot;urn:schemas-microsoft-com:vml&quot;
        ///xmlns:o=&quot;urn:schemas-microsoft-com:office:office&quot;
        ///xmlns:w=&quot;urn:schemas-microsoft-com:office:word&quot;
        ///xmlns:m=&quot;http://schemas.microsoft.com/office/2004/12/omml&quot;
        ///xmlns=&quot;http://www.w3.org/TR/REC-html40&quot;&gt;
        ///
        ///&lt;head&gt;
        ///&lt;meta http-equiv=Content-Type content=&quot;text/html; charset=windows-1252&quot;&gt;
        ///&lt;meta name=ProgId content=Word.Document&gt;
        ///&lt;meta name=Generator content=&quot;Microsoft Word 12&quot;&gt;
        ///&lt;meta name=Originator content=&quot;Microsoft Word 12&quot;&gt;
        ///&lt;link rel=File-List href=&quot;OneStory [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_NetBibleDonateMessage {
            get {
                return ResourceManager.GetString("IDS_NetBibleDonateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-Biblical Stories.
        /// </summary>
        internal static string IDS_NonBibStoriesSet {
            get {
                return ResourceManager.GetString("IDS_NonBibStoriesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No project file was found at the internet repository: {0}{0}{1}{0}{0}Are you sure it there is one in the repository yet?.
        /// </summary>
        internal static string IDS_NoProjectFromInternet {
            get {
                return ResourceManager.GetString("IDS_NoProjectFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Stories.
        /// </summary>
        internal static string IDS_ObsoleteStoriesSet {
            get {
                return ResourceManager.GetString("IDS_ObsoleteStoriesSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://Bob_Eaton:tsc2009@ftp.seedconnect.org/OSE3.1/StoryEditor.exe.manifest.xml.
        /// </summary>
        internal static string IDS_OSEUpgradeServer {
            get {
                return ResourceManager.GetString("IDS_OSEUpgradeServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://Bob_Eaton:tsc2009@ftp.seedconnect.org/OSE3.2/StoryEditor.exe.manifest.xml.
        /// </summary>
        internal static string IDS_OSEUpgradeServerNextMajorUpgrade {
            get {
                return ResourceManager.GetString("IDS_OSEUpgradeServerNextMajorUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://Bob_Eaton:tsc2009@ftp.seedconnect.org.
        /// </summary>
        internal static string IDS_OSEUpgradeServerSword {
            get {
                return ResourceManager.GetString("IDS_OSEUpgradeServerSword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ftp://Bob_Eaton:tsc2009@ftp.seedconnect.org/Test/testmanifest.xml.
        /// </summary>
        internal static string IDS_OSEUpgradeServerTest {
            get {
                return ResourceManager.GetString("IDS_OSEUpgradeServerTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is corrupted. No &apos;StoryCrafterMemberID&apos; record found. Send to bob_eaton@sall.com for help..
        /// </summary>
        internal static string IDS_ProjectFileCorrupted {
            get {
                return ResourceManager.GetString("IDS_ProjectFileCorrupted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file is corrupted. No &apos;CraftingInfo&apos; record found. Send to bob_eaton@sall.com for help..
        /// </summary>
        internal static string IDS_ProjectFileCorruptedNoCraftingInfo {
            get {
                return ResourceManager.GetString("IDS_ProjectFileCorruptedNoCraftingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The project file you&apos;re trying to open (i.e. &apos;{0}&apos;) was lasted edited by an earlier version of the OneStory editor. I can automatically upgrade the project file to be readable by this newer version, but it will make it inaccessible to the earlier version. So if the rest of the team (Project Facilitators, Consultant, etc) have all: a) done a &apos;Project&apos;, &apos;Send/receive&apos; to send all of their outstanding changes, and b) upgraded to the new version of OSE, then if you want the project file to be converted to the n [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_QueryConvertProjectFile1_3to1_4 {
            get {
                return ResourceManager.GetString("IDS_QueryConvertProjectFile1_3to1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A key term or its status has changed. Do you wish to save these changes?.
        /// </summary>
        internal static string IDS_SaveKeyTermsPrompt {
            get {
                return ResourceManager.GetString("IDS_SaveKeyTermsPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \_sh v3.0  374  LnC Note
        ///\_DateStampHasFourDigitYear
        ///
        ///\r
        ///\wrd
        ///\co.
        /// </summary>
        internal static string IDS_TbxFile_EmptyLnC {
            get {
                return ResourceManager.GetString("IDS_TbxFile_EmptyLnC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to \+DatabaseType StoryBT
        ///\ver 5.0
        ///\desc BT and Anchors. Tracks with ConNotes
        ///\+mkrset 
        ///\lngDefault Default
        ///\mkrRecord c
        ///
        ///\+mkr Ro
        ///\nam *
        ///\lng Default
        ///\mkrOverThis c
        ///\-mkr
        ///
        ///\+mkr _DateStampHasFourDigitYear
        ///\nam *
        ///\lng Default
        ///\mkrOverThis c
        ///\-mkr
        ///
        ///\+mkr _sh
        ///\nam *
        ///\lng Default
        ///\mkrOverThis c
        ///\-mkr
        ///
        ///\+mkr anc
        ///\nam Anchor
        ///\lng Default
        ///\+fnt 
        ///\Name Arial Unicode MS
        ///\Size 8
        ///\charset 00
        ///\rgbColor 255,0,0
        ///\-fnt
        ///\mkrOverThis bt
        ///\-mkr
        ///
        ///\+mkr ans
        ///\nam Answers
        ///\lng InternationalBT        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string IDS_TbxFile_StoryBT {
            get {
                return ResourceManager.GetString("IDS_TbxFile_StoryBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to continue! Cause: {0}.
        /// </summary>
        internal static string IDS_UnableToContinue {
            get {
                return ResourceManager.GetString("IDS_UnableToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open the member list{0}{0}{1}{0}{0}Contact bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_UnableToOpenMemberList {
            get {
                return ResourceManager.GetString("IDS_UnableToOpenMemberList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open project &apos;{1}&apos;{0}{0}{2}{0}{0}{3}{0}{0}Send the project file along with the error message to bob_eaton@sall.com for help.
        /// </summary>
        internal static string IDS_UnableToOpenProjectFile {
            get {
                return ResourceManager.GetString("IDS_UnableToOpenProjectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the state customization file (i.e. {0}). If you&apos;ve customized which fields show by default in various states, then you need to delete the version of the customization file in the project folder (i.e. &quot;{1}\{0}&quot;) so the program can re-create it using the newly upgraded version.
        /// </summary>
        internal static string IDS_UnableToOpenStageTransitionsXml {
            get {
                return ResourceManager.GetString("IDS_UnableToOpenStageTransitionsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save the project file &apos;{1}&apos;{0}{0}{2}.
        /// </summary>
        internal static string IDS_UnableToSave {
            get {
                return ResourceManager.GetString("IDS_UnableToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line number &apos;{0}&apos; has multiple sentences in the {1} column. Use the &quot;Story&quot; menu, &quot;Collapse into 1 line&quot; command followed by the &quot;Split into Lines&quot; command to break the story (and any back-translations) into lines based on sentence final punctuation (see &quot;Project&quot;, &quot;Settings&quot; and any of the &quot;Language&quot; tabs to configure sentence final punctuation). The command &quot;Story&quot;, &quot;Re-align story lines&quot; can also be used, which calls both of the above commands in one click.
        /// </summary>
        internal static string IDS_UseStoryCollapse {
            get {
                return ResourceManager.GetString("IDS_UseStoryCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click &apos;Ignore&apos; to overwrite the existing &apos;My Biblical Terms&apos; list with the contents of the &apos;{0}&apos; list. Otherwise, click &apos;Retry&apos; to merge the contents of the &apos;{0}&apos; list into the existing &apos;My Biblical Terms&apos; list..
        /// </summary>
        internal static string IDS_VerifyOverwriteMyBiblicalTerms {
            get {
                return ResourceManager.GetString("IDS_VerifyOverwriteMyBiblicalTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have at least half as many story testing questions as lines in the story. Unless you have prior permission from your consultant, you should click Cancel and add at least {0} more testing question(s). (right-click on the &apos;line options&apos; button and choose &apos;Add a story testing question&apos;). Otherwise, click &apos;Yes&apos; to continue on to the next state..
        /// </summary>
        internal static string IDS_WarnAboutNotEnoughTqs {
            get {
                return ResourceManager.GetString("IDS_WarnAboutNotEnoughTqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        ///	jQuery Autosize v1.16.7
        ///	(c) 2013 Jack Moore - jacklmoore.com
        ///	updated: 2013-03-20
        ///	license: http://www.opensource.org/licenses/mit-license.php
        ///*/
        ///(function(e){var t,o,n={className:&quot;autosizejs&quot;,append:&quot;&quot;,callback:!1},i=&quot;hidden&quot;,s=&quot;border-box&quot;,a=&quot;lineHeight&quot;,l=&apos;&lt;textarea tabindex=&quot;-1&quot; style=&quot;position:absolute; top:-999px; left:0; right:auto; bottom:auto; border:0; -moz-box-sizing:content-box; -webkit-box-sizing:content-box; box-sizing:content-box; word-wrap:break-word; height:0 !important; min-height:0  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_autosize_min {
            get {
                return ResourceManager.GetString("jquery_autosize_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*!
        /// * jQuery JavaScript Library v1.4.2
        /// * http://jquery.com/
        /// *
        /// * Copyright 2010, John Resig
        /// * Dual licensed under the MIT or GPL Version 2 licenses.
        /// * http://jquery.org/license
        /// *
        /// * Includes Sizzle.js
        /// * http://sizzlejs.com/
        /// * Copyright 2010, The Dojo Foundation
        /// * Released under the MIT, BSD, and GPL Licenses.
        /// *
        /// * Date: Sat Feb 13 22:33:48 2010 -0500
        /// */
        ///(function(A,w){function ma(){if(!c.isReady){try{s.documentElement.doScroll(&quot;left&quot;)}catch(a){setTimeout(ma,1);return}c.ready()}}function Qa(a,b){b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string jquery_min {
            get {
                return ResourceManager.GetString("jquery_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE stylesheet [
        ///&lt;!ENTITY cr &quot;&amp;#xD;&amp;#xA;&quot;&gt;
        ///&lt;!ENTITY tab &quot;&amp;#9;&quot;&gt;
        ///&lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
        ///]&gt;
        ///&lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;2.0&quot;&gt;
        ///    &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///    &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///    &lt;!-- oneStory2CoachNotes.xsl         
        ///        create by Bob Eaton based on Jim Albright&apos;s script for storyingBT 
        ///        (to handle conversion of onestory to sfm)
        ///        2010-04-05        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oneStory2CoachNotes {
            get {
                return ResourceManager.GetString("oneStory2CoachNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE stylesheet [
        ///&lt;!ENTITY cr &quot;&amp;#xD;&amp;#xA;&quot;&gt;
        ///&lt;!ENTITY tab &quot;&amp;#9;&quot;&gt;
        ///&lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
        ///]&gt;
        ///&lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;2.0&quot;&gt;
        ///    &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///    &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///    &lt;!-- oneStory2ConNotes.xsl         
        ///        create by Bob Eaton based on Jim Albright&apos;s script for storyingBT 
        ///        (to handle conversion of onestory to sfm)
        ///        2010-04-05
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oneStory2ConNotes {
            get {
                return ResourceManager.GetString("oneStory2ConNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE stylesheet [
        ///&lt;!ENTITY cr &quot;&amp;#xD;&amp;#xA;&quot;&gt;
        ///&lt;!ENTITY tab &quot;&amp;#9;&quot;&gt;
        ///&lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
        ///]&gt;
        ///&lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;2.0&quot;&gt;
        ///    &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///    &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///    &lt;!-- oneStory2KeyTerms.xsl
        ///        create by Bob Eaton based on Jim Albright&apos;s script for storyingBT 
        ///        (to handle conversion of onestory to sfm)
        ///        2010-04-05
        ///        ke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oneStory2KeyTerms {
            get {
                return ResourceManager.GetString("oneStory2KeyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE stylesheet [
        ///&lt;!ENTITY cr &quot;&amp;#xD;&amp;#xA;&quot;&gt;
        ///&lt;!ENTITY tab &quot;&amp;#9;&quot;&gt;
        ///&lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
        ///]&gt;
        ///&lt;xsl:transform version=&quot;2.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///               xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot;
        ///               xmlns:user=&quot;urn:my-scripts&quot;&gt;
        ///  &lt;msxsl:script language=&quot;C#&quot; implements-prefix=&quot;user&quot;&gt;
        ///    &lt;msxsl:assembly name=&quot;System.Windows.Forms&quot; /&gt;
        ///    &lt;![CDATA[
        ///  public string Rtf2Text(string strRtf)
        ///  {
        ///    System.Wind [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oneStory2storyingBT {
            get {
                return ResourceManager.GetString("oneStory2storyingBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;!DOCTYPE stylesheet [
        ///&lt;!ENTITY cr &quot;&amp;#xD;&amp;#xA;&quot;&gt;
        ///&lt;!ENTITY tab &quot;&amp;#9;&quot;&gt;
        ///&lt;!ENTITY nbsp &quot;&amp;#160;&quot;&gt;
        ///]&gt;
        ///&lt;xsl:transform xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; version=&quot;2.0&quot;&gt;
        ///    &lt;xsl:output method=&quot;text&quot; encoding=&quot;UTF-8&quot; indent=&quot;no&quot;/&gt;
        ///    &lt;xsl:strip-space elements=&quot;*&quot;/&gt;
        ///
        ///    &lt;!-- oneStory2storyingRetelling.xsl
        ///        create by Bob Eaton based on Jim Albright&apos;s script for storyingBT 
        ///        (to handle conversion of onestory to sfm)
        ///        2010-04-05
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string oneStory2storyingRetelling {
            get {
                return ResourceManager.GetString("oneStory2storyingRetelling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenSelectedItemHS {
            get {
                object obj = ResourceManager.GetObject("OpenSelectedItemHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PrintHS {
            get {
                object obj = ResourceManager.GetObject("PrintHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:template match=&quot;@* | node()&quot;&gt;
        ///    &lt;xsl:copy&gt;
        ///      &lt;xsl:apply-templates select=&quot;@* | node()&quot;/&gt;
        ///    &lt;/xsl:copy&gt;
        ///  &lt;/xsl:template&gt;
        ///
        ///  &lt;!--StoryProject@version changed from 1.3 to 1.4--&gt;
        ///  &lt;xsl:template match=&quot;StoryProject/@version&quot;&gt;
        ///    &lt;xsl:attribu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string project_1_3_to_1_4 {
            get {
                return ResourceManager.GetString("project_1_3_to_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://msdn2.microsoft.com/en-us/library/az24scfc.aspx.
        /// </summary>
        internal static string RegexHelpProgram {
            get {
                return ResourceManager.GetString("RegexHelpProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ShowAllCommentsHS {
            get {
                object obj = ResourceManager.GetObject("ShowAllCommentsHS", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SplashScreenImage {
            get {
                object obj = ResourceManager.GetObject("SplashScreenImage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;StateTransition stage=&quot;eProjFacTypeFreeTranslation&quot; MemberTypeWithEditToken=&quot;eProjectFacilitator&quot; RequiresUsingFreeTranslation=&quot;true&quot;&gt;
        ///    &lt;StageDisplayString&gt;Project Facilitator enters Free Translation&lt;/StageDisplayString&gt;
        ///    &lt;TransitionDisplayString&gt;enter the Free Translation&lt;/TransitionDisplayString&gt;
        ///    &lt;StageInstructions&gt;
        ///In this stage, you (the project facilitator) will enter the Free translation (FT) of the story.
        ///This Free Translation should be done by a UNS directly and you (the project faci [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StageTransition20Update {
            get {
                return ResourceManager.GetString("StageTransition20Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///    &lt;head&gt;
        ///        &lt;title&gt;&lt;/title&gt;
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///{0}
        ///        &lt;/script&gt;
        ///        &lt;script type=&quot;text/javascript&quot;&gt;
        ///{1}
        ///{2}
        ///        &lt;/script&gt;
        ///{3}
        ///    &lt;/head&gt;
        ///    &lt;body onscroll=&quot;window.external.OnScroll();&quot;&gt;
        ///        &lt;!--for debugging: &lt;textarea id=&quot;osedebughtmlwindow&quot;&gt;&lt;/textarea&gt;--&gt;
        ///{4}
        ///    &lt;/body&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///{5}
        ///&lt;/script&gt;
        ///&lt;/html&gt;.
        /// </summary>
        internal static string StoryBtHtml {
            get {
                return ResourceManager.GetString("StoryBtHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // this one is called from the anchor buttons
        ///function OnBibRefJump(btn) {
        ///    if (event.button == 2) {
        ///        window.external.OnAnchorButton(btn.id);
        ///
        ///        // prevent the OnEmptyAnchorClick from happening too
        ///        event.cancelBubble = true;
        ///    }
        ///    else
        ///        window.external.OnBibRefJump(btn.name);
        ///    return false; // cause the href navigation to not happen
        ///}
        ///// this one is called from the empty cell where the buttons go (for right-click to add Null Button)
        ///function OnEmptyAnchorCl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoryBtJs {
            get {
                return ResourceManager.GetString("StoryBtJs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function VernacularLanguageName() {{
        ///    return &apos;{0}&apos;;
        ///}}
        ///function NationalBtLanguageName() {{
        ///    return &apos;{1}&apos;;
        ///}}
        ///function InternationalBtLanguageName() {{
        ///    return &apos;{2}&apos;;
        ///}}
        ///function FreeTranslationLanguageName() {{
        ///    return &apos;{3}&apos;;
        ///}}.
        /// </summary>
        internal static string StoryBtPlaceholders {
            get {
                return ResourceManager.GetString("StoryBtPlaceholders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var textareas = document.getElementsByTagName(&quot;textarea&quot;);
        ///for (var i = 0; i &lt; textareas.length; i++) {
        ///    // keep this one in this format (as opposed to jscript) since the C# code occasionally calls InvokeMember(&quot;onchange&quot;)
        ///    //  and if we don&apos;t have it in regular java, then C# invoke can&apos;t access it (I think)
        ///    textareas[i].onchange = function() { return window.external.TextareaOnChange(this.id, this.value); };
        ///}
        ///
        ///$(&apos;textarea&apos;).attr(&apos;placeholder&apos;, function () {
        ///    if ($(this).hasClass(&apos;LangV [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StoryBtPsJs {
            get {
                return ResourceManager.GetString("StoryBtPsJs", resourceCulture);
            }
        }
    }
}
