//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4952
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneStoryProjectEditor.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string LastUserType {
            get {
                return ((string)(this["LastUserType"]));
            }
            set {
                this["LastUserType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastNetBibleReference {
            get {
                return ((string)(this["LastNetBibleReference"]));
            }
            set {
                this["LastNetBibleReference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastStoryWorkedOn {
            get {
                return ((string)(this["LastStoryWorkedOn"]));
            }
            set {
                this["LastStoryWorkedOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastMemberLogin {
            get {
                return ((string)(this["LastMemberLogin"]));
            }
            set {
                this["LastMemberLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjects {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjects"]));
            }
            set {
                this["RecentProjects"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProject {
            get {
                return ((string)(this["LastProject"]));
            }
            set {
                this["LastProject"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OneStory Editor Projects")]
        public string DefMyDocsSubfolder {
            get {
                return ((string)(this["DefMyDocsSubfolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentProjectPaths {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentProjectPaths"]));
            }
            set {
                this["RecentProjectPaths"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LastProjectPath {
            get {
                return ((string)(this["LastProjectPath"]));
            }
            set {
                this["LastProjectPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<?xml version=\"1.0\" encoding=\"utf-16\"?>\r\n<ArrayOfString xmlns:xsi=\"http://www.w3." +
            "org/2001/XMLSchema-instance\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\">\r\n  <s" +
            "tring>NETfree</string>\r\n</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection SwordModulesUsed {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["SwordModulesUsed"]));
            }
            set {
                this["SwordModulesUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NETfree")]
        public string LastSwordModuleUsed {
            get {
                return ((string)(this["LastSwordModuleUsed"]));
            }
            set {
                this["LastSwordModuleUsed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SourceFont\r\nHeight\t-19\r\nWidth\t0\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t" +
            "0\r\nUnderline\t0\r\nStrikeOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t3\r\nClipPre" +
            "cision\t2\r\nQuality\t1\r\nPitchAndFamily\t34\r\nFaceName\t{0}\r\nColor\t16711680\r\n\r\nTargetFo" +
            "nt\r\nHeight\t-19\r\nWidth\t0\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t0\r\nUnde" +
            "rline\t0\r\nStrikeOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t3\r\nClipPrecision\t" +
            "2\r\nQuality\t1\r\nPitchAndFamily\t34\r\nFaceName\t{1}\r\nColor\t0\r\n\r\nNavTextFont\r\nHeight\t-1" +
            "5\r\nWidth\t7\r\nEscapement\t0\r\nOrientation\t0\r\nWeight\t700\r\nItalic\t0\r\nUnderline\t0\r\nStri" +
            "keOut\t0\r\nFontEncoding\t33\r\nCharSet\t0\r\nOutPrecision\t1\r\nClipPrecision\t2\r\nQuality\t2\r" +
            "\nPitchAndFamily\t34\r\nFaceName\t{2}\r\nColor\t65280\r\n\r\nProjectSettings\r\nSourceLanguage" +
            "Name\t{3}\r\nTargetLanguageName\t{4}\r\nDefaultCCTablePath\t\r\nLastExportPath\t\r\nLastNewD" +
            "ocumentFolder\t{5}\\Adapt It Unicode Work\r\nPunctuationPairsSourceSet(stores space " +
            "for an empty cell)\t{6}\r\nPunctuationPairsTargetSet(stores space for an empty cell" +
            ")\t{7}\r\n\r\nPunctuationTwoCharacterPairsSourceSet(ditto)\t\r\nPunctuationTwoCharacterP" +
            "airsTargetSet(ditto)\t\r\nSpecialTextColor\t255\r\nRetranslationTextColor\t32896\r\nColor" +
            "OfNavigationText\t65280\r\nBackupDocumentFlag\t0\r\nRTL_Layout\t0\r\nSFMescapeChar\t\\\r\nSFM" +
            "afterNewlines\t0\r\nSourceIsRTL\t{8}\r\nTargetIsRTL\t{9}\r\n\r\nNavTextIsRTL\t0\r\nLowerCaseSo" +
            "urceLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\nUpperCaseSourceLanguageChars\tABCDE" +
            "FGHIJKLMNOPQRSTUVWXYZ\r\nLowerCaseTargetLanguageChars\tabcdefghijklmnopqrstuvwxyz\r\n" +
            "UpperCaseTargetLanguageChars\tABCDEFGHIJKLMNOPQRSTUVWXYZ\r\nLowerCaseGlossLanguageC" +
            "hars\tabcdefghijklmnopqrstuvwxyz\r\nUpperCaseGlossLanguageChars\tABCDEFGHIJKLMNOPQRS" +
            "TUVWXYZ\r\nAutoCapitalizationFlag\t0\r\nSourceHasUpperCaseAndLowerCase\t0\r\nFontSizeFor" +
            "Dialogs(points)\t12\r\nUseSFMarkerSet\tUsfmOnly\r\nUseFilterMarkers\t\\_list_base \\xdc \\" +
            "lit \\_double_boxed_para \\_body_text \\bt \\ef \\x \\_normal_table \\_footnote_caller " +
            "\\_dft_para_font \\h \\_unknown_para_style \\_annotation_ref \\note \\rem \\_annotation" +
            "_text \\_peripherals_base \\_heading_base \\_hdr_ftr_interlinear \\__normal \\xk \\ide" +
            " \\_horiz_rule \\_vernacular_base \\_small_para_break \\mr \\_notes_base \\_nav_lang_i" +
            "nterlinear \\efm \\pro \\restore \\_footer \\xo \\_single_boxed_para \\_src_lang_interl" +
            "inear \\cl \\_unknown_char_style \\ib \\xq \\_header \\vp \\_hidden_note \\_tgt_lang_int" +
            "erlinear \\free \\r \\_gls_lang_interlinear \\ie \\xt \\va \\cp \\h1 \\h2 \\_table_grid \\_" +
            "intro_base \\fig \\ca \\h3 \\rq \r\nChangeFixedSpaceToRegularSpace\t0\r\nBookModeFlag\t0\r\n" +
            "BookIndexValue\t-1\r\nSaveAsXML\t1\r\nSilConverterName\t\r\nSilConverterDirectionForward\t" +
            "1\r\nSilConverterNormalizeOutput\t0\r\nLegacyCopyForPhraseBox\t1\r\nDoAdaptingBeforeGlos" +
            "sing_InVerticalEdit\t1")]
        public string DefaultAIProjectFile {
            get {
                return ((string)(this["DefaultAIProjectFile"]));
            }
            set {
                this["DefaultAIProjectFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""UTF-8"" standalone=""yes""?>
<!--
	 Note: Using Microsoft WORD 2003 or later is not a good way to edit this xml file.
	 Instead, use NotePad, WordPad or Windows Explorer.
	 Please note: the order of the TU elements in this xml file might differ each time the knowledge base is saved. This is not an error. -->
<KB docVersion=""4"" srcName=""{0}"" tgtName=""{1}"" max=""1"">
	<MAP mn=""1"">
	</MAP>
</KB>
")]
        public string DefaultAIKBFile {
            get {
                return ((string)(this["DefaultAIKBFile"]));
            }
            set {
                this["DefaultAIKBFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LastPanoramaViewTabIndex {
            get {
                return ((int)(this["LastPanoramaViewTabIndex"]));
            }
            set {
                this["LastPanoramaViewTabIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgUrl"]));
            }
            set {
                this["ProjectNameToHgUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgUsername {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgUsername"]));
            }
            set {
                this["ProjectNameToHgUsername"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInStoryLanguage {
            get {
                return ((bool)(this["LookInStoryLanguage"]));
            }
            set {
                this["LookInStoryLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInNationalBT {
            get {
                return ((bool)(this["LookInNationalBT"]));
            }
            set {
                this["LookInNationalBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInEnglishBT {
            get {
                return ((bool)(this["LookInEnglishBT"]));
            }
            set {
                this["LookInEnglishBT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInConsultantNotes {
            get {
                return ((bool)(this["LookInConsultantNotes"]));
            }
            set {
                this["LookInConsultantNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInCoachNotes {
            get {
                return ((bool)(this["LookInCoachNotes"]));
            }
            set {
                this["LookInCoachNotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInRetellings {
            get {
                return ((bool)(this["LookInRetellings"]));
            }
            set {
                this["LookInRetellings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInTestQs {
            get {
                return ((bool)(this["LookInTestQs"]));
            }
            set {
                this["LookInTestQs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LookInAllStories {
            get {
                return ((bool)(this["LookInAllStories"]));
            }
            set {
                this["LookInAllStories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseRegEx {
            get {
                return ((bool)(this["UseRegEx"]));
            }
            set {
                this["UseRegEx"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFind {
            get {
                return ((bool)(this["EnableFind"]));
            }
            set {
                this["EnableFind"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LookInExpander {
            get {
                return ((bool)(this["LookInExpander"]));
            }
            set {
                this["LookInExpander"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentFindWhat {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentFindWhat"]));
            }
            set {
                this["RecentFindWhat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection RecentReplaceWith {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["RecentReplaceWith"]));
            }
            set {
                this["RecentReplaceWith"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToHgNetworkUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToHgNetworkUrl"]));
            }
            set {
                this["ProjectNameToHgNetworkUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string BiblicalTermsPath {
            get {
                return ((string)(this["BiblicalTermsPath"]));
            }
            set {
                this["BiblicalTermsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UpgradeSettings {
            get {
                return ((bool)(this["UpgradeSettings"]));
            }
            set {
                this["UpgradeSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LastUseForAllStories {
            get {
                return ((bool)(this["LastUseForAllStories"]));
            }
            set {
                this["LastUseForAllStories"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LookInTestAs {
            get {
                return ((bool)(this["LookInTestAs"]));
            }
            set {
                this["LookInTestAs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point BiblicalTermsDlgLocation {
            get {
                return ((global::System.Drawing.Point)(this["BiblicalTermsDlgLocation"]));
            }
            set {
                this["BiblicalTermsDlgLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BiblicalTermsDlgHeight {
            get {
                return ((int)(this["BiblicalTermsDlgHeight"]));
            }
            set {
                this["BiblicalTermsDlgHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int BiblicalTermsDlgWidth {
            get {
                return ((int)(this["BiblicalTermsDlgWidth"]));
            }
            set {
                this["BiblicalTermsDlgWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PanoramaViewDlgHeight {
            get {
                return ((int)(this["PanoramaViewDlgHeight"]));
            }
            set {
                this["PanoramaViewDlgHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int PanoramaViewDlgWidth {
            get {
                return ((int)(this["PanoramaViewDlgWidth"]));
            }
            set {
                this["PanoramaViewDlgWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Point PanoramaViewDlgLocation {
            get {
                return ((global::System.Drawing.Point)(this["PanoramaViewDlgLocation"]));
            }
            set {
                this["PanoramaViewDlgLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoCheckForProgramUpdatesAtStartup {
            get {
                return ((bool)(this["AutoCheckForProgramUpdatesAtStartup"]));
            }
            set {
                this["AutoCheckForProgramUpdatesAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoSaveTimeoutEnabled {
            get {
                return ((bool)(this["AutoSaveTimeoutEnabled"]));
            }
            set {
                this["AutoSaveTimeoutEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DoAutoSaveSilently {
            get {
                return ((bool)(this["DoAutoSaveSilently"]));
            }
            set {
                this["DoAutoSaveSilently"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutoHideBiblePane {
            get {
                return ((bool)(this["AutoHideBiblePane"]));
            }
            set {
                this["AutoHideBiblePane"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Microsoft Sans Serif")]
        public string StateTransitionFontName {
            get {
                return ((string)(this["StateTransitionFontName"]));
            }
            set {
                this["StateTransitionFontName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public float StateTransitionFontSize {
            get {
                return ((float)(this["StateTransitionFontSize"]));
            }
            set {
                this["StateTransitionFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public long LastPrintSettings {
            get {
                return ((long)(this["LastPrintSettings"]));
            }
            set {
                this["LastPrintSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("small")]
        public string ConNoteTableFontSize {
            get {
                return ((string)(this["ConNoteTableFontSize"]));
            }
            set {
                this["ConNoteTableFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("x-small")]
        public string ConNoteButtonFontSize {
            get {
                return ((string)(this["ConNoteButtonFontSize"]));
            }
            set {
                this["ConNoteButtonFontSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("’”„,")]
        public string RightEdgeQuotes {
            get {
                return ((string)(this["RightEdgeQuotes"]));
            }
            set {
                this["RightEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"\'")]
        public string EitherEdgeQuotes {
            get {
                return ((string)(this["EitherEdgeQuotes"]));
            }
            set {
                this["EitherEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("‘‛“‟")]
        public string LeftEdgeQuotes {
            get {
                return ((string)(this["LeftEdgeQuotes"]));
            }
            set {
                this["LeftEdgeQuotes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>private.languageDepot.org</string>
  <string>http://hg-private.languagedepot.org</string>
  <string>languageDepot.org</string>
  <string>http://hg-public.languagedepot.org</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection AdaptItDefaultServerLabels {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["AdaptItDefaultServerLabels"]));
            }
            set {
                this["AdaptItDefaultServerLabels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToAiHgUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToAiHgUrl"]));
            }
            set {
                this["ProjectNameToAiHgUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Specialized.StringCollection ProjectNameToAiHgNetworkUrl {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ProjectNameToAiHgNetworkUrl"]));
            }
            set {
                this["ProjectNameToAiHgNetworkUrl"] = value;
            }
        }
    }
}
