//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4961
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EditResxLocalization.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EditResxLocalization.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;!--doc1 is the original elf document
        ///      doc2 is the fragment that we want to merge into doc1
        ///  &lt;xsl:variable name=&quot;doc1&quot; select=&quot;document(&apos;C:\src\StoryEditor\EditResxLocalization\Properties\Trash.elf&apos;)&quot; /&gt;
        ///      --&gt;
        ///  &lt;xsl:variable name=&quot;doc1&quot; select=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string elfMerge {
            get {
                return ResourceManager.GetString("elfMerge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization Editor.
        /// </summary>
        internal static string IDS_Caption {
            get {
                return ResourceManager.GetString("IDS_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newly non-obsolete.
        /// </summary>
        internal static string IDS_New {
            get {
                return ResourceManager.GetString("IDS_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Even Newer One.
        /// </summary>
        internal static string IDS_Newer {
            get {
                return ResourceManager.GetString("IDS_Newer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save the Localization file first?.
        /// </summary>
        internal static string IDS_SaveFirstQuery {
            get {
                return ResourceManager.GetString("IDS_SaveFirstQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot;
        ///    xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;
        ///&gt;
        ///  &lt;xsl:output method=&quot;xml&quot; indent=&quot;yes&quot;/&gt;
        ///
        ///  &lt;xsl:param name=&quot;param1&quot;/&gt;
        ///  &lt;xsl:param name=&quot;param2&quot;/&gt;
        ///  &lt;xsl:param name=&quot;param3&quot;/&gt;
        ///
        ///  &lt;xsl:variable name=&quot;languageName&quot; select=&quot;$param1&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;languageId&quot; select=&quot;$param2&quot;/&gt;
        ///  &lt;xsl:variable name=&quot;fallbackId&quot; select=&quot;$param3&quot;/&gt;
        ///  
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string resx2elf {
            get {
                return ResourceManager.GetString("resx2elf", resourceCulture);
            }
        }
    }
}
